# Font configuration
[font]
size = 12.0
offset.y = 1
glyph_offset.x = 0
glyph_offset.y = 0

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "BoldItalic"

# Window configuration
[window]
title = ""
decorations = "None"
opacity = 0.8
dimensions = { columns = 85, lines = 25 }
padding = { x = 0, y = 5 }

# used color now: Tokyo Night
[colors]
[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black = "0x15161E"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

[[colors.indexed_colors]]
index = 16
color = "0xff9e64"

[[colors.indexed_colors]]
index = 17
color = "0xdb4b4b"

[keyboard]
[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Y"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "E"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "G"
mode = "Vi|~Search"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "G"
mods = "Shift"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "B"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "F"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "Copy"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Copy"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "V"
mode = "Vi|~Search"
action = "ToggleNormalSelection"

[[keyboard.bindings]]
key = "V"
mods = "Shift"
mode = "Vi|~Search"
action = "ToggleLineSelection"

[[keyboard.bindings]]
key = "V"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleBlockSelection"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
mode = "Vi|~Search"
action = "ToggleSemanticSelection"

[[keyboard.bindings]]
key = "Return"
mode = "Vi|~Search"
action = "Open"

[[keyboard.bindings]]
key = "Z"
mode = "Vi|~Search"
action = "CenterAroundViCursor"

[[keyboard.bindings]]
key = "K"
mode = "Vi|~Search"
action = "Up"

[[keyboard.bindings]]
key = "J"
mode = "Vi|~Search"
action = "Down"

[[keyboard.bindings]]
key = "H"
mode = "Vi|~Search"
action = "Left"

[[keyboard.bindings]]
key = "L"
mode = "Vi|~Search"
action = "Right"

[[keyboard.bindings]]
key = "Up"
mode = "Vi|~Search"
action = "Up"

[[keyboard.bindings]]
key = "Down"
mode = "Vi|~Search"
action = "Down"

[[keyboard.bindings]]
key = "Left"
mode = "Vi|~Search"
action = "Left"

[[keyboard.bindings]]
key = "Right"
mode = "Vi|~Search"
action = "Right"

[[keyboard.bindings]]
key = "Key0"
mode = "Vi|~Search"
action = "First"

[[keyboard.bindings]]
key = "Key4"
mods = "Shift"
mode = "Vi|~Search"
action = "Last"

[[keyboard.bindings]]
key = "Key6"
mods = "Shift"
mode = "Vi|~Search"
action = "FirstOccupied"

[[keyboard.bindings]]
key = "H"
mods = "Shift"
mode = "Vi|~Search"
action = "High"

[[keyboard.bindings]]
key = "M"
mods = "Shift"
mode = "Vi|~Search"
action = "Middle"

[[keyboard.bindings]]
key = "L"
mods = "Shift"
mode = "Vi|~Search"
action = "Low"

[[keyboard.bindings]]
key = "B"
mode = "Vi|~Search"
action = "SemanticLeft"

[[keyboard.bindings]]
key = "W"
mode = "Vi|~Search"
action = "SemanticRight"

[[keyboard.bindings]]
key = "E"
mode = "Vi|~Search"
action = "SemanticRightEnd"

[[keyboard.bindings]]
key = "B"
mods = "Shift"
mode = "Vi|~Search"
action = "WordLeft"

[[keyboard.bindings]]
key = "W"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRight"

[[keyboard.bindings]]
key = "E"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRightEnd"

[[keyboard.bindings]]
key = "Key5"
mods = "Shift"
mode = "Vi|~Search"
action = "Bracket"

[[keyboard.bindings]]
key = "Slash"
mode = "Vi|~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "Slash"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchBackward"

[[keyboard.bindings]]
key = "N"
mode = "Vi|~Search"
action = "SearchNext"

[[keyboard.bindings]]
key = "N"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchPrevious"

# Search Mode
[[keyboard.bindings]]
key = "Return"
mode = "Search|Vi"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "Escape"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Search"
action = "SearchClear"

[[keyboard.bindings]]
key = "W"
mods = "Control"
mode = "Search"
action = "SearchDeleteWord"

[[keyboard.bindings]]
key = "P"
mods = "Control"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "N"
mods = "Control"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Up"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "Down"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Return"
mode = "Search|~Vi"
action = "SearchFocusNext"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
mode = "Search|~Vi"
action = "SearchFocusPrevious"

[[keyboard.bindings]]
key = "K"
mods = "Command"
mode = "~Vi|~Search"
chars = "\\f"
